# Generated by Django 2.2 on 2019-12-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('construction', 'construction'), ('maintenance', 'maintenance')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('date_started', models.DateField()),
            ],
        ),
    ]
