# Generated by Django 2.2 on 2019-12-20 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_polygonpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('date_formed', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project')),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('date_uploaded', models.DateField()),
                ('is_verified', models.BooleanField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cluster')),
            ],
        ),
    ]
