# Generated by Django 2.2 on 2019-12-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cluster_datapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='date_formed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='date_uploaded',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_started',
            field=models.DateTimeField(),
        ),
    ]
